package com.westee.authservice.generate;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.ID
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.MENU_NAME
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.MENU_PATH
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private String menuPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.ICON
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.PARENT_MENU_ID
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private Integer parentMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.SORT_ORDER
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.CREATED_AT
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MENU.UPDATED_AT
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MENU
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public Menu(Integer id, String menuName, String menuPath, String icon, Integer parentMenuId, Integer sortOrder, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.menuName = menuName;
        this.menuPath = menuPath;
        this.icon = icon;
        this.parentMenuId = parentMenuId;
        this.sortOrder = sortOrder;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public Menu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.ID
     *
     * @return the value of MENU.ID
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.ID
     *
     * @param id the value for MENU.ID
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.MENU_NAME
     *
     * @return the value of MENU.MENU_NAME
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.MENU_NAME
     *
     * @param menuName the value for MENU.MENU_NAME
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.MENU_PATH
     *
     * @return the value of MENU.MENU_PATH
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.MENU_PATH
     *
     * @param menuPath the value for MENU.MENU_PATH
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath == null ? null : menuPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.ICON
     *
     * @return the value of MENU.ICON
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.ICON
     *
     * @param icon the value for MENU.ICON
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.PARENT_MENU_ID
     *
     * @return the value of MENU.PARENT_MENU_ID
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public Integer getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.PARENT_MENU_ID
     *
     * @param parentMenuId the value for MENU.PARENT_MENU_ID
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setParentMenuId(Integer parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.SORT_ORDER
     *
     * @return the value of MENU.SORT_ORDER
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.SORT_ORDER
     *
     * @param sortOrder the value for MENU.SORT_ORDER
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.CREATED_AT
     *
     * @return the value of MENU.CREATED_AT
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.CREATED_AT
     *
     * @param createdAt the value for MENU.CREATED_AT
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MENU.UPDATED_AT
     *
     * @return the value of MENU.UPDATED_AT
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MENU.UPDATED_AT
     *
     * @param updatedAt the value for MENU.UPDATED_AT
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}