package com.westee.authservice.generate;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLES
     *
     * @mbg.generated Sat Jan 20 16:25:10 CST 2024
     */
    int updateByPrimaryKey(Role record);
}