package com.westee.goodsservice.entity;

import com.westee.goodsservice.generate.Cake;
import com.westee.goodsservice.generate.CakeTag;

import java.time.LocalDateTime;
import java.util.ArrayList;

public class CakeWithTag extends Cake {
    private ArrayList<CakeTag> tags;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE
     *
     * @param id
     * @param name
     * @param imgUrl
     * @param deleted
     * @param createdAt
     * @param updatedAt
     * @mbg.generated Fri Jul 28 14:34:59 CST 2023
     */
    public CakeWithTag(Long id, String name, String imgUrl, Boolean deleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(id, name, imgUrl, deleted, createdAt, updatedAt);
    }

    public ArrayList<CakeTag> getTags() {
        return tags;
    }

    public void setTags(ArrayList<CakeTag> tags) {
        this.tags = tags;
    }
}
