CREATE TABLE MENU
(
    ID             INT AUTO_INCREMENT PRIMARY KEY,
    MENU_NAME      VARCHAR(100) NOT NULL,
    MENU_PATH      VARCHAR(255),
    ICON           VARCHAR(50),
    PARENT_MENU_ID INT,
    SORT_ORDER     INT,
    CREATED_AT     TIMESTAMP DEFAULT NOW(),
    UPDATED_AT     TIMESTAMP DEFAULT NOW()
);

INSERT INTO MENU (MENU_NAME, MENU_PATH, ICON, PARENT_MENU_ID, SORT_ORDER, CREATED_AT, UPDATED_AT)
VALUES ('Home', '/home', 'home_icon.png', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);