CREATE TABLE WX_EXPRESS
(
    ID               BIGINT    NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ERRCODE          INT(11) DEFAULT NULL,
    ERRMSG           VARCHAR(255)       DEFAULT NULL,
    APPID            VARCHAR(255)       DEFAULT NULL,
    WX_STORE_ID      VARCHAR(255)       DEFAULT NULL,
    WX_ORDER_ID      VARCHAR(255)       DEFAULT NULL,
    STORE_ORDER_ID   VARCHAR(255)       DEFAULT NULL,
    SERVICE_TRANS_ID VARCHAR(255)       DEFAULT NULL,
    DISTANCE         INT(11) DEFAULT NULL,
    FEE              INT(11) DEFAULT NULL,
    TRANS_ORDER_ID   VARCHAR(255)       DEFAULT NULL,
    ORDER_STATUS     VARCHAR(6),
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP NOT NULL DEFAULT NOW()
);