CREATE TABLE `EXPRESS_INFO`
(
    ID          bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID    BIGINT,
    WX_ORDER_NO varchar(60),
    INFO        varchar(1000),
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;