ALTER TABLE `ORDER_TABLE`
    ADD `PHONE` VARCHAR(20) AFTER `CREATED_AT`;

ALTER TABLE ORDER_TABLE
    ADD PICK_UP_TIME DATETIME DEFAULT CURRENT_TIMESTAMP NULL;

ALTER TABLE `ORDER_TABLE`
    ADD `FINAL_AMOUNT` DECIMAL(12, 2) AFTER `TOTAL_PRICE`;

ALTER TABLE `ORDER_TABLE`
    ADD `DISCOUNT_ID` BIGINT AFTER `FINAL_AMOUNT`;