CREATE TABLE CONFIG
(
    ID                  INT PRIMARY KEY AUTO_INCREMENT,
    BUSINESS_START_TIME TIME           NOT NULL,
    BUSINESS_END_TIME   TIME           NOT NULL,
    FREE_EXPRESS_AMOUNT DECIMAL(10, 2) NOT NULL,
    STORE_CLOSE_START   DATE                    DEFAULT NULL,
    STORE_CLOSE_END     DATE                    DEFAULT NULL,
    SHOP_NAME           VARCHAR(100),
    SHOP_ADDRESS        VARCHAR(100),
    CREATED_AT          TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT          TIMESTAMP      NOT NULL DEFAULT NOW()
);

INSERT INTO CONFIG (BUSINESS_START_TIME, BUSINESS_END_TIME, FREE_EXPRESS_AMOUNT, STORE_CLOSE_START, STORE_CLOSE_END)
VALUES ('09:00:00', '18:00:00', 100.00, '2023-09-23', '2023-09-30');