CREATE TABLE CHARGE_OPTION
(
    ID           INT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(20),
    AMOUNT       DECIMAL,
    GIFT         DECIMAL, -- 赠送金额
    DELETED      BOOLEAN            DEFAULT FALSE,
    OWNER_USR_ID BIGINT,
    SHOP_ID      BIGINT,
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMP NOT NULL DEFAULT NOW()
);