CREATE TABLE GOODS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_ID BIGINT,
    NAME        VARCHAR(100),
    DESCRIPTION VARCHAR(1024),
    DETAILS     TEXT,
    WEIGHT      INT NULL,
    GOODS_TYPE  INT NULL,
    IMG_URL     VARCHAR(1024),
    PRICE       DECIMAL(12, 2),
    VIP_PRICE   DECIMAL(12, 2),
    SHOP_ID     BIGINT,
    STOCK       INT       NOT NULL DEFAULT 0,
    STATUS      VARCHAR(16),
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT NOW()
);