CREATE TABLE DISCOUNT_DAY
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    GOODS_ID   BIGINT  NOT NULL,
    DISCOUNT   DECIMAL(2, 2) DEFAULT NULL,              -- 打折
    PRICE      DECIMAL(12, 2) DEFAULT NULL,             -- 或者指定价格
    DAYS       VARCHAR(100) NOT NULL,                        -- '1,2,3,4,5,6,7'
    DISABLED   BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);