CREATE TABLE CAKE_TAG
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(100),
    DELETED    BOOLEAN            DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE CAKE
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(100),
    IMG_URL    VARCHAR(1024),
    DELETED    BOOLEAN            DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE CAKE_TAG_MAPPING
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    CAKE_ID    VARCHAR(100),
    TAG_ID     VARCHAR(1024),
    DELETED    BOOLEAN            DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);