CREATE TABLE SWIPER
(
    ID          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE       VARCHAR(255)             DEFAULT NULL,
    IMAGE_URL   VARCHAR(255)    NOT NULL,
    SWIPER_TYPE VARCHAR(10)              DEFAULT 'index',
    LINK_URL    VARCHAR(255)             DEFAULT NULL,
    SORT_ORDER  INT             NOT NULL DEFAULT '0',
    ENABLED     BOOLEAN                  default TRUE NOT NULL,
    CREATED_AT  TIMESTAMP       NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP       NOT NULL DEFAULT NOW()
);