
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8082
spring:
  application:
    name: openfeign
