package com.westee.orderservice.generate;

import com.westee.orderservice.generate.ExpressInfo;
import com.westee.orderservice.generate.ExpressInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ExpressInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    long countByExample(ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int deleteByExample(ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int insert(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int insertSelective(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    List<ExpressInfo> selectByExample(ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    ExpressInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int updateByExampleSelective(@Param("record") ExpressInfo record, @Param("example") ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int updateByExample(@Param("record") ExpressInfo record, @Param("example") ExpressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int updateByPrimaryKeySelective(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPRESS_INFO
     *
     * @mbg.generated Thu Mar 07 21:05:33 CST 2024
     */
    int updateByPrimaryKey(ExpressInfo record);
}