package com.westee.orderservice.generate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class OrderTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.USER_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.TOTAL_PRICE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.FINAL_AMOUNT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private BigDecimal finalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.DISCOUNT_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private Long discountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.ADDRESS_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.EXPRESS_COMPANY
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String expressCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.EXPRESS_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String expressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.WX_ORDER_NO
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String wxOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.PAY_TYPE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.PICKUP_TYPE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private Byte pickupType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.PICKUP_CODE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String pickupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.SHOP_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.STATUS
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.CREATED_AT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.PHONE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.UPDATED_AT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_TABLE.PICK_UP_TIME
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private LocalDateTime pickUpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDER_TABLE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_TABLE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public OrderTable(Long id, Long userId, BigDecimal totalPrice, BigDecimal finalAmount, Long discountId, Long addressId, String expressCompany, String expressId, String wxOrderNo, String payType, Byte pickupType, String pickupCode, Long shopId, String status, LocalDateTime createdAt, String phone, LocalDateTime updatedAt, LocalDateTime pickUpTime) {
        this.id = id;
        this.userId = userId;
        this.totalPrice = totalPrice;
        this.finalAmount = finalAmount;
        this.discountId = discountId;
        this.addressId = addressId;
        this.expressCompany = expressCompany;
        this.expressId = expressId;
        this.wxOrderNo = wxOrderNo;
        this.payType = payType;
        this.pickupType = pickupType;
        this.pickupCode = pickupCode;
        this.shopId = shopId;
        this.status = status;
        this.createdAt = createdAt;
        this.phone = phone;
        this.updatedAt = updatedAt;
        this.pickUpTime = pickUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_TABLE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public OrderTable() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.ID
     *
     * @return the value of ORDER_TABLE.ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.ID
     *
     * @param id the value for ORDER_TABLE.ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.USER_ID
     *
     * @return the value of ORDER_TABLE.USER_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.USER_ID
     *
     * @param userId the value for ORDER_TABLE.USER_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.TOTAL_PRICE
     *
     * @return the value of ORDER_TABLE.TOTAL_PRICE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.TOTAL_PRICE
     *
     * @param totalPrice the value for ORDER_TABLE.TOTAL_PRICE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.FINAL_AMOUNT
     *
     * @return the value of ORDER_TABLE.FINAL_AMOUNT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public BigDecimal getFinalAmount() {
        return finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.FINAL_AMOUNT
     *
     * @param finalAmount the value for ORDER_TABLE.FINAL_AMOUNT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setFinalAmount(BigDecimal finalAmount) {
        this.finalAmount = finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.DISCOUNT_ID
     *
     * @return the value of ORDER_TABLE.DISCOUNT_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public Long getDiscountId() {
        return discountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.DISCOUNT_ID
     *
     * @param discountId the value for ORDER_TABLE.DISCOUNT_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setDiscountId(Long discountId) {
        this.discountId = discountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.ADDRESS_ID
     *
     * @return the value of ORDER_TABLE.ADDRESS_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.ADDRESS_ID
     *
     * @param addressId the value for ORDER_TABLE.ADDRESS_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.EXPRESS_COMPANY
     *
     * @return the value of ORDER_TABLE.EXPRESS_COMPANY
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.EXPRESS_COMPANY
     *
     * @param expressCompany the value for ORDER_TABLE.EXPRESS_COMPANY
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany == null ? null : expressCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.EXPRESS_ID
     *
     * @return the value of ORDER_TABLE.EXPRESS_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.EXPRESS_ID
     *
     * @param expressId the value for ORDER_TABLE.EXPRESS_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setExpressId(String expressId) {
        this.expressId = expressId == null ? null : expressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.WX_ORDER_NO
     *
     * @return the value of ORDER_TABLE.WX_ORDER_NO
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getWxOrderNo() {
        return wxOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.WX_ORDER_NO
     *
     * @param wxOrderNo the value for ORDER_TABLE.WX_ORDER_NO
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setWxOrderNo(String wxOrderNo) {
        this.wxOrderNo = wxOrderNo == null ? null : wxOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.PAY_TYPE
     *
     * @return the value of ORDER_TABLE.PAY_TYPE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.PAY_TYPE
     *
     * @param payType the value for ORDER_TABLE.PAY_TYPE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.PICKUP_TYPE
     *
     * @return the value of ORDER_TABLE.PICKUP_TYPE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public Byte getPickupType() {
        return pickupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.PICKUP_TYPE
     *
     * @param pickupType the value for ORDER_TABLE.PICKUP_TYPE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setPickupType(Byte pickupType) {
        this.pickupType = pickupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.PICKUP_CODE
     *
     * @return the value of ORDER_TABLE.PICKUP_CODE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getPickupCode() {
        return pickupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.PICKUP_CODE
     *
     * @param pickupCode the value for ORDER_TABLE.PICKUP_CODE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setPickupCode(String pickupCode) {
        this.pickupCode = pickupCode == null ? null : pickupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.SHOP_ID
     *
     * @return the value of ORDER_TABLE.SHOP_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.SHOP_ID
     *
     * @param shopId the value for ORDER_TABLE.SHOP_ID
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.STATUS
     *
     * @return the value of ORDER_TABLE.STATUS
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.STATUS
     *
     * @param status the value for ORDER_TABLE.STATUS
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.CREATED_AT
     *
     * @return the value of ORDER_TABLE.CREATED_AT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.CREATED_AT
     *
     * @param createdAt the value for ORDER_TABLE.CREATED_AT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.PHONE
     *
     * @return the value of ORDER_TABLE.PHONE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.PHONE
     *
     * @param phone the value for ORDER_TABLE.PHONE
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.UPDATED_AT
     *
     * @return the value of ORDER_TABLE.UPDATED_AT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.UPDATED_AT
     *
     * @param updatedAt the value for ORDER_TABLE.UPDATED_AT
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_TABLE.PICK_UP_TIME
     *
     * @return the value of ORDER_TABLE.PICK_UP_TIME
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public LocalDateTime getPickUpTime() {
        return pickUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_TABLE.PICK_UP_TIME
     *
     * @param pickUpTime the value for ORDER_TABLE.PICK_UP_TIME
     *
     * @mbg.generated Sat Mar 09 11:12:32 CST 2024
     */
    public void setPickUpTime(LocalDateTime pickUpTime) {
        this.pickUpTime = pickUpTime;
    }
}