package com.westee.orderservice.generate;

import java.io.Serializable;
import java.time.LocalDateTime;

public class WxExpress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.ERRCODE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private Integer errcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.ERRMSG
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String errmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.APPID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.WX_STORE_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String wxStoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.WX_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String wxOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.STORE_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String storeOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.SERVICE_TRANS_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String serviceTransId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.DISTANCE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private Integer distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.FEE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private Integer fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.TRANS_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String transOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.ORDER_STATUS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.CREATED_AT
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WX_EXPRESS.UPDATED_AT
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public WxExpress(Long id, Integer errcode, String errmsg, String appid, String wxStoreId, String wxOrderId, String storeOrderId, String serviceTransId, Integer distance, Integer fee, String transOrderId, String orderStatus, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.errcode = errcode;
        this.errmsg = errmsg;
        this.appid = appid;
        this.wxStoreId = wxStoreId;
        this.wxOrderId = wxOrderId;
        this.storeOrderId = storeOrderId;
        this.serviceTransId = serviceTransId;
        this.distance = distance;
        this.fee = fee;
        this.transOrderId = transOrderId;
        this.orderStatus = orderStatus;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public WxExpress() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.ID
     *
     * @return the value of WX_EXPRESS.ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.ID
     *
     * @param id the value for WX_EXPRESS.ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.ERRCODE
     *
     * @return the value of WX_EXPRESS.ERRCODE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public Integer getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.ERRCODE
     *
     * @param errcode the value for WX_EXPRESS.ERRCODE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setErrcode(Integer errcode) {
        this.errcode = errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.ERRMSG
     *
     * @return the value of WX_EXPRESS.ERRMSG
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.ERRMSG
     *
     * @param errmsg the value for WX_EXPRESS.ERRMSG
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg == null ? null : errmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.APPID
     *
     * @return the value of WX_EXPRESS.APPID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.APPID
     *
     * @param appid the value for WX_EXPRESS.APPID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.WX_STORE_ID
     *
     * @return the value of WX_EXPRESS.WX_STORE_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getWxStoreId() {
        return wxStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.WX_STORE_ID
     *
     * @param wxStoreId the value for WX_EXPRESS.WX_STORE_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setWxStoreId(String wxStoreId) {
        this.wxStoreId = wxStoreId == null ? null : wxStoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.WX_ORDER_ID
     *
     * @return the value of WX_EXPRESS.WX_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getWxOrderId() {
        return wxOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.WX_ORDER_ID
     *
     * @param wxOrderId the value for WX_EXPRESS.WX_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setWxOrderId(String wxOrderId) {
        this.wxOrderId = wxOrderId == null ? null : wxOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.STORE_ORDER_ID
     *
     * @return the value of WX_EXPRESS.STORE_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getStoreOrderId() {
        return storeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.STORE_ORDER_ID
     *
     * @param storeOrderId the value for WX_EXPRESS.STORE_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setStoreOrderId(String storeOrderId) {
        this.storeOrderId = storeOrderId == null ? null : storeOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.SERVICE_TRANS_ID
     *
     * @return the value of WX_EXPRESS.SERVICE_TRANS_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getServiceTransId() {
        return serviceTransId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.SERVICE_TRANS_ID
     *
     * @param serviceTransId the value for WX_EXPRESS.SERVICE_TRANS_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setServiceTransId(String serviceTransId) {
        this.serviceTransId = serviceTransId == null ? null : serviceTransId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.DISTANCE
     *
     * @return the value of WX_EXPRESS.DISTANCE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.DISTANCE
     *
     * @param distance the value for WX_EXPRESS.DISTANCE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.FEE
     *
     * @return the value of WX_EXPRESS.FEE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.FEE
     *
     * @param fee the value for WX_EXPRESS.FEE
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.TRANS_ORDER_ID
     *
     * @return the value of WX_EXPRESS.TRANS_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getTransOrderId() {
        return transOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.TRANS_ORDER_ID
     *
     * @param transOrderId the value for WX_EXPRESS.TRANS_ORDER_ID
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setTransOrderId(String transOrderId) {
        this.transOrderId = transOrderId == null ? null : transOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.ORDER_STATUS
     *
     * @return the value of WX_EXPRESS.ORDER_STATUS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.ORDER_STATUS
     *
     * @param orderStatus the value for WX_EXPRESS.ORDER_STATUS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.CREATED_AT
     *
     * @return the value of WX_EXPRESS.CREATED_AT
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.CREATED_AT
     *
     * @param createdAt the value for WX_EXPRESS.CREATED_AT
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WX_EXPRESS.UPDATED_AT
     *
     * @return the value of WX_EXPRESS.UPDATED_AT
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WX_EXPRESS.UPDATED_AT
     *
     * @param updatedAt the value for WX_EXPRESS.UPDATED_AT
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}