package com.westee.orderservice.generate;

import com.westee.orderservice.generate.WxExpress;
import com.westee.orderservice.generate.WxExpressExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WxExpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    long countByExample(WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int deleteByExample(WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int insert(WxExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int insertSelective(WxExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    List<WxExpress> selectByExample(WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    WxExpress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") WxExpress record, @Param("example") WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int updateByExample(@Param("record") WxExpress record, @Param("example") WxExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int updateByPrimaryKeySelective(WxExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_EXPRESS
     *
     * @mbg.generated Thu Mar 07 21:05:01 CST 2024
     */
    int updateByPrimaryKey(WxExpress record);
}