spring:
  application:
    name: eureka-server

server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    #    service-url:
    #      defaultZone: http://localhost:8698/eureka,http://localhost:8699/eureka  # http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false # ??????????Eureka???
    fetch-registry: false  # ?????Eureka???????????
  server:
    renewal-percent-threshold: 0.49 # ??0.85
