package com.westee.goodsservice.generate;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CakeTag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAKE_TAG.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAKE_TAG.NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAKE_TAG.DELETED
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAKE_TAG.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAKE_TAG.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public CakeTag(Long id, String name, Boolean deleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public CakeTag() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAKE_TAG.ID
     *
     * @return the value of CAKE_TAG.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAKE_TAG.ID
     *
     * @param id the value for CAKE_TAG.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAKE_TAG.NAME
     *
     * @return the value of CAKE_TAG.NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAKE_TAG.NAME
     *
     * @param name the value for CAKE_TAG.NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAKE_TAG.DELETED
     *
     * @return the value of CAKE_TAG.DELETED
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAKE_TAG.DELETED
     *
     * @param deleted the value for CAKE_TAG.DELETED
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAKE_TAG.CREATED_AT
     *
     * @return the value of CAKE_TAG.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAKE_TAG.CREATED_AT
     *
     * @param createdAt the value for CAKE_TAG.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAKE_TAG.UPDATED_AT
     *
     * @return the value of CAKE_TAG.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAKE_TAG.UPDATED_AT
     *
     * @param updatedAt the value for CAKE_TAG.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}