package com.westee.goodsservice.generate;

import com.westee.goodsservice.generate.CakeTag;
import com.westee.goodsservice.generate.CakeTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CakeTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    long countByExample(CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByExample(CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insert(CakeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insertSelective(CakeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    List<CakeTag> selectByExample(CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    CakeTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") CakeTag row, @Param("example") CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExample(@Param("row") CakeTag row, @Param("example") CakeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKeySelective(CakeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKey(CakeTag row);
}