package com.westee.goodsservice.generate;

import com.westee.goodsservice.generate.CakeTagMapping;
import com.westee.goodsservice.generate.CakeTagMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CakeTagMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    long countByExample(CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByExample(CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insert(CakeTagMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insertSelective(CakeTagMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    List<CakeTagMapping> selectByExample(CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    CakeTagMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") CakeTagMapping row, @Param("example") CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExample(@Param("row") CakeTagMapping row, @Param("example") CakeTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKeySelective(CakeTagMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAKE_TAG_MAPPING
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKey(CakeTagMapping row);
}