package com.westee.goodsservice.generate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class Charge implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CHARGE_TYPE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.AMOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.REMARK
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.STATUS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.PRESENT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private BigDecimal present;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.WX_OUT_TRADE_NO
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String wxOutTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARGE.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHARGE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Charge(Long id, Long userId, String chargeType, BigDecimal amount, String remark, String status, BigDecimal present, String wxOutTradeNo, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.userId = userId;
        this.chargeType = chargeType;
        this.amount = amount;
        this.remark = remark;
        this.status = status;
        this.present = present;
        this.wxOutTradeNo = wxOutTradeNo;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Charge() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.ID
     *
     * @return the value of CHARGE.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.ID
     *
     * @param id the value for CHARGE.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.USER_ID
     *
     * @return the value of CHARGE.USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.USER_ID
     *
     * @param userId the value for CHARGE.USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CHARGE_TYPE
     *
     * @return the value of CHARGE.CHARGE_TYPE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CHARGE_TYPE
     *
     * @param chargeType the value for CHARGE.CHARGE_TYPE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.AMOUNT
     *
     * @return the value of CHARGE.AMOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.AMOUNT
     *
     * @param amount the value for CHARGE.AMOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.REMARK
     *
     * @return the value of CHARGE.REMARK
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.REMARK
     *
     * @param remark the value for CHARGE.REMARK
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.STATUS
     *
     * @return the value of CHARGE.STATUS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.STATUS
     *
     * @param status the value for CHARGE.STATUS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.PRESENT
     *
     * @return the value of CHARGE.PRESENT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public BigDecimal getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.PRESENT
     *
     * @param present the value for CHARGE.PRESENT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setPresent(BigDecimal present) {
        this.present = present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.WX_OUT_TRADE_NO
     *
     * @return the value of CHARGE.WX_OUT_TRADE_NO
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getWxOutTradeNo() {
        return wxOutTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.WX_OUT_TRADE_NO
     *
     * @param wxOutTradeNo the value for CHARGE.WX_OUT_TRADE_NO
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setWxOutTradeNo(String wxOutTradeNo) {
        this.wxOutTradeNo = wxOutTradeNo == null ? null : wxOutTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.CREATED_AT
     *
     * @return the value of CHARGE.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.CREATED_AT
     *
     * @param createdAt the value for CHARGE.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARGE.UPDATED_AT
     *
     * @return the value of CHARGE.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARGE.UPDATED_AT
     *
     * @param updatedAt the value for CHARGE.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}