package com.westee.goodsservice.generate;

import com.westee.goodsservice.generate.ChargeOption;
import com.westee.goodsservice.generate.ChargeOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChargeOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    long countByExample(ChargeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByExample(ChargeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insert(ChargeOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insertSelective(ChargeOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    List<ChargeOption> selectByExample(ChargeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    ChargeOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") ChargeOption row, @Param("example") ChargeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExample(@Param("row") ChargeOption row, @Param("example") ChargeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKeySelective(ChargeOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHARGE_OPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKey(ChargeOption row);
}