package com.westee.goodsservice.generate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

public class Config implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.BUSINESS_START_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalTime businessStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.BUSINESS_END_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalTime businessEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private BigDecimal freeExpressAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.STORE_CLOSE_START
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDate storeCloseStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.STORE_CLOSE_END
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDate storeCloseEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.SHOP_NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.SHOP_ADDRESS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String shopAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONFIG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Config(Integer id, LocalTime businessStartTime, LocalTime businessEndTime, BigDecimal freeExpressAmount, LocalDate storeCloseStart, LocalDate storeCloseEnd, String shopName, String shopAddress, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.businessStartTime = businessStartTime;
        this.businessEndTime = businessEndTime;
        this.freeExpressAmount = freeExpressAmount;
        this.storeCloseStart = storeCloseStart;
        this.storeCloseEnd = storeCloseEnd;
        this.shopName = shopName;
        this.shopAddress = shopAddress;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIG
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Config() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.ID
     *
     * @return the value of CONFIG.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.ID
     *
     * @param id the value for CONFIG.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.BUSINESS_START_TIME
     *
     * @return the value of CONFIG.BUSINESS_START_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalTime getBusinessStartTime() {
        return businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.BUSINESS_START_TIME
     *
     * @param businessStartTime the value for CONFIG.BUSINESS_START_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setBusinessStartTime(LocalTime businessStartTime) {
        this.businessStartTime = businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.BUSINESS_END_TIME
     *
     * @return the value of CONFIG.BUSINESS_END_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalTime getBusinessEndTime() {
        return businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.BUSINESS_END_TIME
     *
     * @param businessEndTime the value for CONFIG.BUSINESS_END_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setBusinessEndTime(LocalTime businessEndTime) {
        this.businessEndTime = businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @return the value of CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public BigDecimal getFreeExpressAmount() {
        return freeExpressAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @param freeExpressAmount the value for CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setFreeExpressAmount(BigDecimal freeExpressAmount) {
        this.freeExpressAmount = freeExpressAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.STORE_CLOSE_START
     *
     * @return the value of CONFIG.STORE_CLOSE_START
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDate getStoreCloseStart() {
        return storeCloseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.STORE_CLOSE_START
     *
     * @param storeCloseStart the value for CONFIG.STORE_CLOSE_START
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setStoreCloseStart(LocalDate storeCloseStart) {
        this.storeCloseStart = storeCloseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.STORE_CLOSE_END
     *
     * @return the value of CONFIG.STORE_CLOSE_END
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDate getStoreCloseEnd() {
        return storeCloseEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.STORE_CLOSE_END
     *
     * @param storeCloseEnd the value for CONFIG.STORE_CLOSE_END
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setStoreCloseEnd(LocalDate storeCloseEnd) {
        this.storeCloseEnd = storeCloseEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.SHOP_NAME
     *
     * @return the value of CONFIG.SHOP_NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.SHOP_NAME
     *
     * @param shopName the value for CONFIG.SHOP_NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.SHOP_ADDRESS
     *
     * @return the value of CONFIG.SHOP_ADDRESS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getShopAddress() {
        return shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.SHOP_ADDRESS
     *
     * @param shopAddress the value for CONFIG.SHOP_ADDRESS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress == null ? null : shopAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.CREATED_AT
     *
     * @return the value of CONFIG.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.CREATED_AT
     *
     * @param createdAt the value for CONFIG.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.UPDATED_AT
     *
     * @return the value of CONFIG.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.UPDATED_AT
     *
     * @param updatedAt the value for CONFIG.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}