package com.westee.goodsservice.generate;

import com.westee.goodsservice.generate.Coupon;
import com.westee.goodsservice.generate.CouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    long countByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insert(Coupon row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insertSelective(Coupon row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    List<Coupon> selectByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    Coupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") Coupon row, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExample(@Param("row") Coupon row, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKeySelective(Coupon row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKey(Coupon row);
}