package com.westee.goodsservice.generate;

import com.westee.goodsservice.generate.DiscountDay;
import com.westee.goodsservice.generate.DiscountDayExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DiscountDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    long countByExample(DiscountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByExample(DiscountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insert(DiscountDay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insertSelective(DiscountDay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    List<DiscountDay> selectByExample(DiscountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    DiscountDay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") DiscountDay row, @Param("example") DiscountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExample(@Param("row") DiscountDay row, @Param("example") DiscountDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKeySelective(DiscountDay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT_DAY
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKey(DiscountDay row);
}