package com.westee.goodsservice.generate;

import com.westee.goodsservice.generate.Discount;
import com.westee.goodsservice.generate.DiscountExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    long countByExample(DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByExample(DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insert(Discount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int insertSelective(Discount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    List<Discount> selectByExample(DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    Discount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExampleSelective(@Param("row") Discount row, @Param("example") DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByExample(@Param("row") Discount row, @Param("example") DiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKeySelective(Discount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISCOUNT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    int updateByPrimaryKey(Discount row);
}