package com.westee.goodsservice.generate;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Shop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.LATITUDE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.LONGITUDE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.DESCRIPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.IMG_URL
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.OWNER_USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.STATUS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SHOP
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Shop(Long id, String name, Float latitude, Float longitude, String description, String imgUrl, Long ownerUserId, String status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.description = description;
        this.imgUrl = imgUrl;
        this.ownerUserId = ownerUserId;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Shop() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.ID
     *
     * @return the value of SHOP.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.ID
     *
     * @param id the value for SHOP.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.NAME
     *
     * @return the value of SHOP.NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.NAME
     *
     * @param name the value for SHOP.NAME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.LATITUDE
     *
     * @return the value of SHOP.LATITUDE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.LATITUDE
     *
     * @param latitude the value for SHOP.LATITUDE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.LONGITUDE
     *
     * @return the value of SHOP.LONGITUDE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.LONGITUDE
     *
     * @param longitude the value for SHOP.LONGITUDE
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.DESCRIPTION
     *
     * @return the value of SHOP.DESCRIPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.DESCRIPTION
     *
     * @param description the value for SHOP.DESCRIPTION
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.IMG_URL
     *
     * @return the value of SHOP.IMG_URL
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.IMG_URL
     *
     * @param imgUrl the value for SHOP.IMG_URL
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.OWNER_USER_ID
     *
     * @return the value of SHOP.OWNER_USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.OWNER_USER_ID
     *
     * @param ownerUserId the value for SHOP.OWNER_USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.STATUS
     *
     * @return the value of SHOP.STATUS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.STATUS
     *
     * @param status the value for SHOP.STATUS
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.CREATED_AT
     *
     * @return the value of SHOP.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.CREATED_AT
     *
     * @param createdAt the value for SHOP.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.UPDATED_AT
     *
     * @return the value of SHOP.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.UPDATED_AT
     *
     * @param updatedAt the value for SHOP.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}