package com.westee.goodsservice.generate;

import java.io.Serializable;
import java.time.LocalDateTime;

public class UserCoupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.COUPON_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.USED
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private Boolean used;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.USED_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime usedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_COUPON.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public UserCoupon(Long id, Long userId, Long couponId, Boolean used, LocalDateTime usedTime, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.userId = userId;
        this.couponId = couponId;
        this.used = used;
        this.usedTime = usedTime;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_COUPON
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public UserCoupon() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.ID
     *
     * @return the value of USER_COUPON.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.ID
     *
     * @param id the value for USER_COUPON.ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.USER_ID
     *
     * @return the value of USER_COUPON.USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.USER_ID
     *
     * @param userId the value for USER_COUPON.USER_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.COUPON_ID
     *
     * @return the value of USER_COUPON.COUPON_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.COUPON_ID
     *
     * @param couponId the value for USER_COUPON.COUPON_ID
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.USED
     *
     * @return the value of USER_COUPON.USED
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public Boolean getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.USED
     *
     * @param used the value for USER_COUPON.USED
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUsed(Boolean used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.USED_TIME
     *
     * @return the value of USER_COUPON.USED_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.USED_TIME
     *
     * @param usedTime the value for USER_COUPON.USED_TIME
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUsedTime(LocalDateTime usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.CREATED_AT
     *
     * @return the value of USER_COUPON.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.CREATED_AT
     *
     * @param createdAt the value for USER_COUPON.CREATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_COUPON.UPDATED_AT
     *
     * @return the value of USER_COUPON.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_COUPON.UPDATED_AT
     *
     * @param updatedAt the value for USER_COUPON.UPDATED_AT
     *
     * @mbg.generated Mon Jan 29 21:45:20 CST 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}