#spring:
#datasource:
#driver-class-name: com.mysql.cj.jdbc.Driver
#url: jdbc:mysql://127.0.0.1:3306/sc-cake?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#username: root
#password: root

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sc-cake?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

#mybatis:
#config-location: classpath:db/mybatis/mybatis-config.xml


mybatis.config-location=classpath:db/mybatis/mybatis-config.xml

#shiro-redis:
#enabled: true
#redis-manager:
#host: 127.0.0.1:6379


shiro-redis.enabled=true
shiro-redis.redis-manager.host=127.0.0.1:6379